name: Backup All Branches to Specified Repository

on:
  workflow_dispatch:  # 手动触发工作流
  schedule:
    - cron: '0 0 * * *'  # 每天触发一次工作流，可以根据需要修改时间

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2
      with:
        repository: Jinnrry/PMail  # 替换为源仓库
        token: ${{ secrets.GH_TOKEN }}
        fetch-depth: 0  # Fetch all branches

    - name: Setup Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: List all branches
      id: list-branches
      run: |
        git branch -r | grep -v '\->' | sed 's/origin\///' > branches.txt
        cat branches.txt

    - name: Backup each branch
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        BACKUP_REPO: makebl/PMail  # 替换为你的备份仓库
      run: |
        while read branch; do
          git checkout $branch
          git push --force https://$GH_TOKEN@github.com/$BACKUP_REPO.git $branch
        done < branches.txt
