name: Fork Project

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天 0 点运行

jobs:
  fork:
    runs-on: ubuntu-latest
    steps:
      - name: Fork the project
        uses: peter-evans/fork@v3
        with:
          repo: "https://github.com/Jinnrry/PMail"  # 要 fork 的项目
          destination: "https://github.com/Jinnrry/PMail"  # 您的 fork 目标仓库
